### PR TITLE
Update packages doc

### PR DESCRIPTION
**Pull request by TrueFurby**
I used emojis in `Supported` column for better overview of package status.

### CODE REVIEW

**Comment by shurcooL** [comment]
Actually, here's an idea. The current version looks nice when rendered as markdown, but it's not so nice in raw markdown form.

What about replacing the emoji with unicode symbols. So:

```
:white_check_mark:
:ballot_box_with_check:
:x:
```

Becomes:

```
✅
☑️
❌
```

**Comment by flimzy** [comment]
> becomes:

> ✅
> ☑️
> ❌

My 2¢, I like the colored icons better, even though it renders the MD less readable in raw form.

Maybe a compromise would be something like:

    runtime            | :ballot_box_with_check: partially |
    -- cgo             | :x:                     no        |

or

    runtime            | :ballot_box_with_check: | partially |
    -- cgo             | :x:                     | no        |

**Comment by flimzy** [comment]
(Disregard my comment; the same icons show up as colorized when not in a blockquote)

**Comment by shurcooL** [comment]
Here's a gist of what I mean:

https://gist.github.com/shurcooL/26998a997d87c3d775be9fc0a691b440

See its raw format (as it would show up in one's text editor):

https://gist.githubusercontent.com/shurcooL/26998a997d87c3d775be9fc0a691b440/raw/731215df11c27c066a6ccb595c6297bfe2af13d7/packages.md

**Comment by TrueFurby** [comment]
I have changed `☑️ partially` to `❓ partially` since that shows as emoji and the one before did not.

**Comment by shurcooL** [comment]
> since that shows as emoji and the one before did not.

Check the [update to my gist](https://gist.github.com/shurcooL/26998a997d87c3d775be9fc0a691b440/revisions). Apparently there are two ways to encode that unicode symbol, and one shows up prettier than the other:

image

**Comment by TrueFurby** [comment]
Alright. Then is question which one is more relevant the the status **partially**.

This: ☑️ or this: ❓

**Comment by shurcooL** [comment]
I seem to strongly prefer ☑️, especially because of how it fits in between the "✅ yes" and "❌ no". Using❓ implies uncertainty to me, when in fact we're certain that those packages are partially supported.

**Comment by TrueFurby** [comment]
To be honest as I think about it, neither fits the status for me. But I see your logic. 

I've committed the change.

**Comment by shurcooL** [comment]
I've improved alignment slightly in 932e8b0422626af2bfd2ed5874f5eb1cb6008960, hope that's okay (let me know if not).

**Comment by TrueFurby** [comment]
Seem of as well just to the right side now. It's probably because of the width of those symbols. 

I don't really think it matters at all, most of the people will display it here in github anyway where it doesn't make a difference after Markdown and in nobody will care about the extra space in raw format anyway.

I think it's good enough now.

**Comment by shurcooL** [comment]
Yep, LGTM. I can merge if @neelance is okay with this.

**Comment by shurcooL** [comment]
@neelance, why not squash these 5 commits into one on master? They were just iterations during this PR.

**Comment by neelance** [comment]
Honestly I didn't check the commits. Rebase+merge is my default. Do you want to squash and force push or keep it as is?

**Comment by dominikh** [comment]
Do not force push.

**Comment by shurcooL** [comment]
Force pushing to master is not an option, I wanted to raise it for next time.

I think for most logical PRs that do 1 thing, squashing into one commit should be the default, **unless** the author has carefully split it up into logical commits with nice commit messages that are more valuable to keep than squash.

**Comment by neelance** [comment]
@dominikh Haha yeah, I agree with that. I just didn't put it that boldly. ;-)

**Pull request merged**
