### PR TITLE
Circle CI script improvements.

### PR DESCRIPTION
**Pull request by shurcooL**
See individual commit messages.

### CODE REVIEW

**Comment by dominikh** [comment]
What's the reason for skipping examples?

**Comment by shurcooL** [comment]
> What's the reason for skipping examples?

Is the commit message unclear about that?

They currently don't run because gopherjs tool skips them, and they can't run because #381 is unresolved.

This change simply updates the Circle CI script to better match reality (that all examples are skipped).

**Comment by dominikh** [comment]
> Is the commit message unclear about that?

No, that was my fault, sorry. It's late and I forgot to read past the first line.

**Comment by shurcooL** [comment]
No problem. I blame GitHub for hiding commit messages (detailed) by default in PRs.

**Comment by neelance** [comment]
LGTM

**Pull request merged**
