### PR TITLE
compiler: Improve display of import errors.

### LINKED ISSUE #290: "cannot find package" errors could be more informative
Consider this error from `gopherjs build`:

    cannot find package "github.com/flimzy/flashback/pages" in any of:
            /usr/local/go/src/github.com/flimzy/flashback/pages (from $GOROOT)
            /home/jonhall/go/src/github.com/flimzy/flashback/pages (from $GOPATH)

It's *almost* identical to the same error from `go build`:

    cmd/server/server.go:4:2: cannot find package "oink" in any of:
            /usr/local/go/src/oink (from $GOROOT)
            /home/jonhall/go/src/oink (from $GOPATH)

Except that the `go` version tells me where the missing dependency is referenced ("cmd/server.go:4:2").

It would be very handy if GopherJS did the same thing :)

### PR DESCRIPTION
**Pull request by shurcooL**
If there are multiple import errors, display up to 10 of them.

Include the filename and line number where the error occurred, just as go tool does. Resolves #290 (which was a regression caused by #119).

#### Effect

Sample error output before:

```
$ gopherjs build 
cannot find package "foo/bar" in any of:
	/usr/local/go/src/foo/bar (from $GOROOT)
	/Users/Dmitri/Dropbox/Work/2013/GoLanding/src/foo/bar (from $GOPATH)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/foo/bar
```

After this PR:

```
$ gopherjs build 
main.go:3:8: could not import foo/bar (cannot find package "foo/bar" in any of:
	/usr/local/go/src/foo/bar (from $GOROOT)
	/Users/Dmitri/Dropbox/Work/2013/GoLanding/src/foo/bar (from $GOPATH)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/foo/bar)
main.go:4:8: could not import doesnt/exist (cannot find package "doesnt/exist" in any of:
	/usr/local/go/src/doesnt/exist (from $GOROOT)
	/Users/Dmitri/Dropbox/Work/2013/GoLanding/src/doesnt/exist (from $GOPATH)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/doesnt/exist)
```

For comparison, output of `go build`:

```
$ go build
main.go:4:8: cannot find package "doesnt/exist" in any of:
	/usr/local/go/src/doesnt/exist (from $GOROOT)
	/Users/Dmitri/Dropbox/Work/2013/GoLanding/src/doesnt/exist (from $GOPATH)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/doesnt/exist
main.go:3:8: cannot find package "foo/bar" in any of:
	/usr/local/go/src/foo/bar (from $GOROOT)
	/Users/Dmitri/Dropbox/Work/2013/GoLanding/src/foo/bar (from $GOPATH)
	/Users/Dmitri/Dropbox/Work/2013/GoLand/src/foo/bar
```

#### Implementation Notes

Unfortunately, it required me to add more code rather than remove existing code (e.g., by reverting https://github.com/gopherjs/gopherjs/commit/642a7f3fafe4dc7c01179a830271aadd54641fdd). I hope we can eventually be able to reuse `go` tool with `gopherjs` compiler and not have to worry about/maintain this code. So if this works okay, it should be good enough until then.

#### `go1.5gotypes` Branch

If this PR is merged into `master`, I'll need to merge it to `go1.5gotypes` branch as well.

### CODE REVIEW

**Comment by neelance** [comment]
The changes look reasonable. Could you please also check the case that there is an error in a dependency, not in the main package? Because there was the case that it was showing something like `main.go:4:8: foo.go:7:2: error message`.

**Comment by shurcooL** [comment]
Good idea.

I tried this invalid Go program:

```Go
package main

import "fmt"

func main() {
	fmt.Fprintln("Hello")
}
```

The output on this branch and on `master` is identical:

```
$ gopherjs build
main.go:6:15: cannot pass argument "Hello" (constant of type string) to parameter of type io.Writer
```

**Comment by neelance** [comment]
That's not yet a test for an error in a dependency, right?

**Comment by shurcooL** [comment]
It's not. I misread your comment, my mistake.

I'll have to test that later, I'm not on a computer now.

**Comment by shurcooL** [comment]
You were right, it doesn't handle it well when there's a build error in a dependency. Compare:

```
31 $ go build
# github.com/shurcooL/htmlg
../../htmlg/htmlg.go:35: a.AppendChildx undefined (type *"golang.org/x/net/html".Node has no field or method AppendChildx)

31 $ gopherjs build # master
../../htmlg/htmlg.go:35:2: invalid operation: a (variable of type *golang.org/x/net/html.Node) has no field or method AppendChildx

31 $ gopherjs build # this branch
main.go:6:2: could not import github.com/shurcooL/htmlg (/Users/Dmitri/Dropbox/Work/2013/GoLand/src/github.com/shurcooL/htmlg/htmlg.go:35:2: invalid operation: a (variable of type *golang.org/x/net/html.Node) has no field or method AppendChildx)
```

I'll work on fixing that.

**Comment by shurcooL** [comment]
I'm also seeing different behavior depending if you do `gopherjs build` vs. `gopherjs build full/import/path`. It's really odd. This is not an easy fix.

**Comment by shurcooL** [comment]
Files the above as https://github.com/gopherjs/gopherjs/issues/312, and it'd probably need to be resolved before this issue. However, I'm considering closing this PR because I hope we'll eventually be able to use `go` tool and this doesn't seem to be worth spending much time on (because it's tricky to fix and requires a lot of manual regression testing).

**Comment by neelance** [comment]
@shurcooL Have you any specific plan on how to use the `go` tool with GopherJS? How feasible is it?

**Comment by shurcooL** [comment]
I think it's a potential proposal that has a chance of being accepted, on the grounds that currently `go` tool supports 2 Go compilers, and it'd be more general if it didn't have to hard-code them, instead allowing other compilers to be supported if they follow the same schema.

I also know there's quite a bit of hard-coded flags that have gccgo in the names, so it might be hard to outright replace those with more general compiler-agnostic flags or env vars. It might be rejected because of that.

I haven't yet looked into the technical details of how hard, how many changes it would be to make `go` support arbitrary compilers. I suspect it'd be a pretty significant undertaking. But I also think it may happen within the next few years, not necessarily very soon.

**Comment by neelance** [comment]
Given that timeframe, it would still be nice to find a short-term solution for #290.

**Comment by neelance** [comment]
@shurcooL This PR is stale, I'd like to close it. We still have #290 to keep track of the issue.

**Comment by shurcooL** [comment]
Yeah, we can close it. I gave up. When I tried it, it was quite difficult to create a solution that would output optimal error cases in every situation, and I didn't have an automated way of testing different setups, so it was like whack-a-mole, improving errors for one situation would potentially mess them up for another.

By now, trying to resolve this issue from scratch (with this PR as some reference) will be about as hard as trying to pick up this PR.

I do think the best way to resolve this problem will be to start adding some test cases for error messages in order to avoid regressions, and to try to resolve the issue at a lower level than trying to fix it up at higher level.

**Comment by neelance** [comment]
> whack-a-mole

;-)

**Pull request closed without merging**
