### PR TITLE
Fix possible panic during internalization/externalization of time.Time/Date.

### LINKED ISSUE #279: Error with time.Sleep
if use gopherjs with time.Sleep without any reference to time.Time structure, this code:
```go
package main

import (
    "time"

    "github.com/gopherjs/gopherjs/js"
)

//var _ = time.Now()

func log(i ...interface{}) {
    js.Global.Get("console").Call("log", i...)
}

type Test struct {
    A int
    B string
}

func main() {
    log(Test{1, "hello"})
    time.Sleep(time.Second)
}
```

produces error in browser:
```
go-js.js:1738: Uncaught TypeError: Cannot read property 'ptr' of undefined
```
in function $externalize
```js
    if (timePkg && v.constructor === timePkg.Time.ptr) {
```
timePkg.Time is not defined in javascript code

### PR DESCRIPTION
**Pull request by shurcooL**
Begin by adding a failing test for issue #279.

Proper testing for this issue prevents "testing" package from being imported. So, implement it as a low level single file .go test and invoke it from backend. (See #284 for related context.)

In the `time_inexternalization.go`, you can use these statements for
manual testing:

```Go
var _ = time.Now()      // Force time.Time not to be DCEed.
var _ = time.Unix(0, 0) // Force time.Unix (and time.Time implicitly) not to be DCEed.
```

Adding both of those statements (or just `time.Unix` one, since it also includes `time.Time` indirectly) would cause the test to pass. But a true fix will be in the compiler itself, in a way that will avoid the panics/incorrect behavior even when `time.Time` and/or `time.Unix` are DCEed, or time package is not imported at all.

**Edit:** Implemented fix for the issue, so it now resolves #279.

### CODE REVIEW

**Comment by shurcooL** [comment]
Test is currently failing with:

```
lowlevel_test.go:20: exec: "gopherjs": executable file not found in $PATH:
```

@neelance, since you're more familiar with Circle CI (I am more familiar with Travis), do you know how we can make it so the compiled `gopherjs` binary is added to PATH?

**Comment by shurcooL** [comment]
I've implemented a fix for issue #279 that successfully resolves the failing test, please see and review #286.

**Comment by neelance** [comment]
Looks like a good test for the issue. LGTM

**Comment by shurcooL** [comment]
This is ready to merge now and resolves the issue fully. LGTM.

**Comment by shurcooL** [comment]
(I've reworded the second last commit to have a slightly better commit message. It went from "Internalize Date when time package not imported in a reasonable way." to "Internalize Date in a reasonable way when time package not imported.")

**Pull request merged**
