### PR TITLE
- convert thrown errors to go errors

### PR DESCRIPTION
**Pull request by pjebs**
You cans see that having a number at the end of the function is idiomatic.

https://golang.org/pkg/reflect/#Value.Slice3

### CODE REVIEW

**Comment by pjebs** [comment]
@dmitshur @flimzy Why is the unit test failing?

**Comment by pjebs** [comment]
@neelance

**Comment by pjebs** [comment]
It's not about how easy it is to create a workaround function.
If we're programming JS applications in Go, we want JS functions to behave and look like Go code. That means Exceptions need to be converted to error return values.

**Comment by flimzy** [comment]
I think I agree with @nevkontakte. Making a new function version for every function that might panic will be very noisy, and cumbersome to use.

My preference is for a helper function that wraps a function that may panic, and returns an error.  I think that is more maintainable, and also may look a bit more like a JS Try/Catch block, which is pretty close to what it is.  Maybe we even call it `Try()`?

**Comment by pjebs** [comment]
I can do that

**Comment by flimzy** [comment]
Based on the last comment, it seems that an alternative approach was agreed on.  Further, this PR has now sat idle for about a year and a half, so I think it's fair to close it, and apply the alternate approach in a new PR.  If anyone disagrees, we can of course re-open it.

**Pull request closed without merging**
