### PR TITLE
Go 1.10 support (version bump to GopherJS 1.10-1).

### LINKED ISSUE #725: Go 1.10 support.
This is an issue to track work to support Go 1.10. [`go1.10beta1`](https://groups.google.com/forum/#!topic/golang-announce/Zc6kgP2VzhY) has been released today.

I plan to explore this in the next few coming days.

### PR DESCRIPTION
**Pull request by shurcooL**
This PR adds support for Go 1.10, which [has been released today](https://blog.golang.org/go1.10).

It is passing CI ✅ on Linux (see [here](https://circleci.com/gh/gopherjs/gopherjs/1344)), and all tests are passing on macOS for me locally (aside from an unrelated upstream issue https://github.com/golang/go/issues/23881). It's fully ready for testing and review!

(I have not tested it on Windows and can't guarantee support there.)

I've been testing the `go1.10` branch on all of my GopherJS packages during the last few weeks, and there are no known show-stoppers at this time.

The aspirational plan is to merge this sometime next week, after it has a chance to go through review and additional testing, unless major show-stopping issues are discovered and take longer to fix. Minor non-critical issues don't need to be resolved as part of this PR, they can be worked on post-release. But any viable opportunities to improve code can be applied.

Please see issue #725 for context. Each individual commit has a commit message that describes what it's doing.

Resolves #725.

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
Amazing work, as usual @shurcooL. I'll try this out on my projects today and let you know if I run into any problems.

**Comment by johanbrandhorst** [comment]
All good here, excited to have this merged when you're happy to do so.

**Comment by shurcooL** [comment]
This PR has been open for a week, and there've been no code review comments, nor issues reported.

I'm reverting a temporary hacky fix in commit c4db7b2ec4f61a91265715577fcbab8164f676f2 that was applied for debugging purposes (reverted in commit 88dc1afc34049c3bacb1e63667948dab41d9a677), and opening #763 to track progress on resolving that issue. It's not a blocker for release: it only affects reflect code that touches methods sets that include exported methods starting with non-ASCII letters, which is rare.

Then, I'm going to bump the version from "GopherJS 1.10-wip" to "GopherJS 1.10-1" and merge this soon thereafter.

The GopherJS Playground will be updated afterwards.

**Comment by myitcv** [comment]
@shurcooL - apologies, not had much time recently, hence not had a chance to look at the detail of this PR.

For what it's worth I've just tried this out against my React work (links just above this comment) and all looks ok, both for regular files and minified output.

**Comment by shurcooL** [comment]
GopherJS 1.10-1 is now released and available on `master` branch.

Blog post: https://medium.com/gopherjs/gopherjs-1-10-1-is-released-2ff9002a6712.

Tweet: https://twitter.com/GopherJS/status/968207925477965824.

GopherJS Playground has been updated: https://gopherjs.github.io/playground/#/UdyEyAtguS.

Thanks everyone! 🎉 🏄‍♂️

**Pull request merged**
