### PR TITLE
Remove unused argument 'direct'

### PR DESCRIPTION
**Pull request by hajimehoshi**
@shurcooL PTAL

### CODE REVIEW

**Comment by theclapp** [comment]
FWIW, LGTM.  I see no references to `direct` in the function itself or use of it when called, either, in [compiler/statements.go#L444](https://github.com/gopherjs/gopherjs/blob/master/compiler/statements.go#L444).

**Comment by shurcooL** [comment]
Where are the places that call function `$go`? Do they pass 2 or 3 parameters? If 3, we should remove the 3rd parameter from the call sites as well.

**Comment by shurcooL** [comment]
Looking at some generated .js code, I see that all places that call `$go` provide 2 parameters.

I'll try to find in history when `direct` was added and removed so we have more context on this.

**Comment by shurcooL** [comment]
There are only 2 places that generate $go calls:

https://github.com/gopherjs/gopherjs/blob/415225646bb92c4449bb484646f2c95a98402f6f/compiler/statements.go#L444

https://github.com/gopherjs/gopherjs/blob/415225646bb92c4449bb484646f2c95a98402f6f/compiler/compiler.go#L171

Both provide only 2 arguments.

It has been that way ever since go statement support was added in https://github.com/gopherjs/gopherjs/commit/cf716756eec6bc4a64d99c1227aa5178c622df37.

Going to look where `direct` parameter was added, because it wasn't there originally.

**Comment by shurcooL** [comment]
`direct` was added in 3afebab303ea8bdfb55ca4d71d28375dd0ddefd3 and _was used_ then. Let's see when it stopped being used in `$go`...

**Comment by shurcooL** [comment]
2d0acd02933cf349b065398c73490a14f7d9bada is the key commit. It removed uses of `direct` from `$go` function and callers, but forgot to remove it as a parameter.

**Comment by theclapp** [comment]
Nice detective work, @shurcooL.

**Comment by shurcooL** [comment]
Merged. Thanks again!

I didn't merge sooner because I wanted to give a few days for anyone to leave any comments, but then forgot about it. If there's been no activity for more than 7 days, a friendly ping is welcome and appreciated.

**Pull request merged**
