### PR TITLE
WIP: Fix unicode/utf8 issue.

### PR DESCRIPTION
**Pull request by shurcooL**
Do not merge. This is a WIP initial attempt to find a good fix for #319.

I have an initial attempt that seems to maybe kinda partially work to fix the exact reproduce case, but it needs to be significantly reviewed and generalized.

I think I have a test that correctly catches the issue.

### CODE REVIEW

**Comment by shurcooL** [comment]
I am fairly confident in the test being correct.

The externalization case likely makes sense.

The internalization fix is a complete hack and most likely incorrect in the general case. I just pushed it for now, but will continue to look into it later.

At a high level, I'd like to learn more about the current strategy that GopherJS uses to internalize/externalize strings, and discuss some ideas for how ECMAScript 6 features may potentially be useful in improving it (related to #320).

**Comment by shurcooL** [comment]
Well, both the externalization and internalization fixes broke a lot of tests, so they're clearly incomplete/incorrect. It does fix the original issue though:

image

They also resolve the `TestInternalizeExternalizeUnicodeString` test. But need to fix all other tests.

**Comment by shurcooL** [comment]
Resolved in c67fada883858bf571530da0400bb7db3a8d52fe by adding support for UTF-8 surrogate pairs.

@neelance, I'd still like to do this sometime:

> At a high level, I'd like to learn more about the current strategy that GopherJS uses to internalize/externalize strings, and discuss some ideas for how ECMAScript 6 features may potentially be useful in improving it (related to #320).

Also, thoughts on updating to Node 4.x as done in this PR, since it is supported as of https://github.com/gopherjs/gopherjs/commit/d942555ec097c1b3260ed89fff69afc2ceb93bec?

**Comment by neelance** [comment]
@shurcooL Internally, GopherJS uses JS strings, but with a "one character per byte" policy. This fits better to how most operations on strings work. We can adopt ES6 features if they improve performance and we can include a polyfill for them.

**Comment by shurcooL** [comment]
Can you elaborate on "one character per byte" policy? I'm not quite sure what that means.

As an example, how would it represent the Go string `"Hello, 世界. 😀!"`?

In Go, that string is 20 bytes but 13 runes.

**Comment by neelance** [comment]
That string would have 20 characters in the internal JS representation, one for each byte. So if `s` is this string, then `s.length === 20` holds.

**Comment by shurcooL** [comment]
Oh, so "one JavaScript character per Go byte". Gotcha, thanks.

**Pull request closed without merging**
