### PR TITLE
compiler/natives/src/syscall: fix broken build

### PR DESCRIPTION
**Pull request by findleyr**
The CopyBytesToJS function added in gopherjs/gopherjs#1019 does not
compile. Correct it to what I think is the original intent.

### CODE REVIEW

**Comment by nevkontakte** [comment]
```diff
diff --git a/compiler/natives/src/syscall/js/js.go b/compiler/natives/src/syscall/js/js.go
index 8604fb90..ad1141aa 100644
--- a/compiler/natives/src/syscall/js/js.go
+++ b/compiler/natives/src/syscall/js/js.go
@@ -299,7 +299,7 @@ func CopyBytesToGo(dst []byte, src Value) int {
 // It returns the number of bytes copied, which will be the minimum of the lengths of src and dst.
 // CopyBytesToJS panics if dst is not an Uint8Array.
 func CopyBytesToJS(dst Value, src []byte) int {
-	t, ok := dst.v.Interface().([]byte)
+	dt, ok := dst.v.Interface().([]byte)
 	if !ok {
 		panic("syscall/js: CopyBytesToJS: expected dst to be an Uint8Array")
 	}
diff --git a/gopherjs b/gopherjs
new file mode 100644
index 00000000..b73fd387
Binary files /dev/null and b/gopherjs differ

```

**Comment by nevkontakte** [comment]
```diff
diff --git a/compiler/natives/src/syscall/js/js.go b/compiler/natives/src/syscall/js/js.go
index 8604fb90..ad1141aa 100644
--- a/compiler/natives/src/syscall/js/js.go
+++ b/compiler/natives/src/syscall/js/js.go
@@ -299,7 +299,7 @@ func CopyBytesToGo(dst []byte, src Value) int {
 // It returns the number of bytes copied, which will be the minimum of the lengths of src and dst.
 // CopyBytesToJS panics if dst is not an Uint8Array.
 func CopyBytesToJS(dst Value, src []byte) int {
-	t, ok := dst.v.Interface().([]byte)
+	dt, ok := dst.v.Interface().([]byte)
 	if !ok {
 		panic("syscall/js: CopyBytesToJS: expected dst to be an Uint8Array")
 	}

```

**Comment by nevkontakte** [comment]
Thanks for the fix! I've noticed there's still a small typo remaining, could you please incorporate the fix above?

**Comment by findleyr** [comment]
> I've noticed there's still a small typo remaining

Oops, indeed. Nice catch, thanks! Fixed.

**Comment by dmitshur** [comment]
Does the https://github.com/gopherjs/gopherjs/blob/master/compiler/natives/fs_vfsdata.go file need to be regenerated? If it's not, this change only has effect when `gopherjs` is built with `gopherjsdev` build constraint.

**Review by dmitshur — APPROVED** [review]
Thanks. Not finding issues in this change.

**Comment by nevkontakte** [comment]
Thanks all!

**Comment by findleyr** [comment]
Thanks!

**Pull request merged**
