### PR TITLE
Remove unnecessary assignments

### PR DESCRIPTION
**Pull request by hajimehoshi**

### CODE REVIEW

**Comment by shurcooL** [comment]
This seems to break CI pretty badly. Are you sure they're unnecessary assignments?

**Comment by hajimehoshi** [comment]
I've just read the code and this seemed just assignments to unused local variables. I'm not sure why CI complains.

**Comment by hajimehoshi** [comment]
`go test ./...` passed on my local machine. It looks like the CI just timed out. Is it possible to retry the CI?

**Comment by shurcooL** [comment]
`go test ./...` is not all the tests, see [here](https://github.com/gopherjs/gopherjs/blob/415225646bb92c4449bb484646f2c95a98402f6f/circle.yml#L21-L134) for all tests that run in CI.

Sure, I can restart CI. However, it looks like it timed out because the execution wasn't making progress. Look at these entries in the log:

```
=== RUN   Test1
--- PASS: Test1 (0.00s)
=== RUN   Test1
--- PASS: Test1 (0.00s)
=== RUN   Test1
--- PASS: Test1 (0.00s)
=== RUN   Test1
--- PASS: Test1 (0.00s)
=== RUN   Test1
--- PASS: Test1 (0.00s)
=== RUN   Test1
--- PASS: Test1 (0.00s)
=== RUN   Test1
--- PASS: Test1 (0.00s)
=== RUN   Test1
--- PASS: Test1 (0.00s)
=== RUN   Test1
--- PASS: Test1 (0.00s)
=== RUN   Test1
--- PASS: Test1 (0.00s)
=== RUN   Test1
--- PASS: Test1 (0.00s)
=== RUN   Test1
--- PASS: Test1 (0.00s)
=== RUN   Test1
--- PASS: Test1 (0.00s)
=== RUN   Test1
--- PASS: Test1 (0.00s)
=== RUN   Test1
--- PASS: Test1 (0.00s)
=== RUN   Test1
--- PASS: Test1 (0.00s)
=== RUN   Test1
--- PASS: Test1 (0.00s)
...
```

I've restarted it at https://circleci.com/gh/gopherjs/gopherjs/1287.

**Comment by shurcooL** [comment]
> I've just read the code and this seemed just assignments to unused local variables.

As far as I understand, they're not local variables, they're the parameters to `$go` function. So I'm guessing that changing their value affects the caller of `$go`.

**Comment by hajimehoshi** [comment]
I don't think so? https://jsfiddle.net/rfs18h25/

**Comment by shurcooL** [comment]
Interesting. It seems that removing them does break GopherJS, just look at the output of the [restarted CI job](https://circleci.com/gh/gopherjs/gopherjs/1287).

**Comment by shurcooL** [comment]
If you look at the code, it has some additional complexity, namely there's a `var $goroutine = function() {` and things like `$curGoroutine = $goroutine;`, as well as `$schedule($goroutine);`. So I suspect the variables are indeed used on this line:

```JS
var r = fun.apply(undefined, args);
```

Even though it's hard to see directly due to callbacks...

**Comment by hajimehoshi** [comment]
Ah ok, the variables are reused by calling the callback again. That is tricky, but makes sense...

Thank you for reviewing.

**Comment by shurcooL** [comment]
Thanks for contributing!

If you're interested, feel free to see if `direct` is truly unused and can be safely removed.

**Pull request closed without merging**
