### PR TITLE
compiler/prelude: move prelude to separate .js files

### PR DESCRIPTION
**Pull request by myitcv**
I've been working with the prelude quite a lot recently. One of the really painful things with the current implementation is that the JavaScript for the prelude exists as a `const` string in a `.go` file, which makes properly writing and formatting the Javascript itself very difficult.

This PR splits the prelude into separate `.js` files therefore and adds a `formatpreludejs.go` `go generate`-er to format those `.js` files in place.

### CODE REVIEW

**Comment by myitcv** [comment]
@hajimehoshi @shurcooL - yes, #791 (this PR) is ready for review. It's fully rebased on top of the most recent changes in #784.

As I mentioned in #793 we need to make a decision on whether we merge:

* #784 followed by #791 
* #791 directly (and skip #784)

or something else.

**Comment by myitcv** [comment]
This has now been rebased against `master`

**Comment by flimzy** [comment]
Is this still relevant?  Will it remain relevant if we switch to Go 1.16's use of `embed` for js files?

Thoughts @nevkontakte ?

**Comment by flimzy** [comment]
As this PR is no longer mergable, and will need to effectively be done from scratch, I'm going to close it.

Further, @nevkontakte and I have discussed this, and he has some good ideas on improving the prelude handling which will render this PR obsolete, so he'll soon file a new issue to track progress on this front.

**Pull request closed without merging**
